apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefoods-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubefoods
  template:
    metadata:
      labels:
        app: kubefoods
    spec:
      containers:
      - name: backend
        # Image real ser√° seteada por el workflow con `kubectl set image`
        image: ghcr.io/<OWNER>/kubefoods-backend:stable
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5